import { notFound, redirect } from "next/navigation";
import { auth } from "@/../auth";
import { getModerationPaper } from "@/server/submissions";
import { approveSubmission, approveSubmissionWithEdits, rejectSubmission } from "@/app/submit/actions";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";

export default async function ModerationDetail({ params }: { params: Promise<{ id: string }> }) {
  const session = await auth();
  if (session?.user?.role !== "ADMIN") redirect("/login?callbackUrl=/admin/moderation");
  const paper = await getModerationPaper((await params).id);
  if (!paper) notFound();
  const ids = (key: "authors" | "advisors" | "keywords" | "technologies") => paper[key].map((item) => "author" in item ? item.author : "advisor" in item ? item.advisor : "keyword" in item ? item.keyword : item.technology).map((item) => item.id).join(",");
  return <main><div className="mb-6"><h1 className="text-3xl font-bold">ตรวจสอบภาคนิพนธ์</h1><p className="mt-1 text-muted-foreground">ตรวจข้อมูลต้นฉบับทางซ้าย และแก้ไขก่อนอนุมัติทางขวา</p></div><div className="grid gap-6 lg:grid-cols-2"><section className="rounded-lg border bg-muted/30 p-5"><h2 className="text-xl font-semibold">ข้อมูลที่ส่งมา</h2><dl className="mt-4 space-y-3 text-sm"><div><dt className="font-medium">ชื่อเรื่อง</dt><dd>{paper.titleTh}</dd></div><div><dt className="font-medium">บทคัดย่อ</dt><dd className="whitespace-pre-wrap leading-6">{paper.abstractTh}</dd></div><div><dt className="font-medium">หมวด</dt><dd>{paper.researchArea.nameTh}</dd></div><div><dt className="font-medium">สิทธิ์</dt><dd>{paper.accessLevel}</dd></div></dl><form action={rejectSubmission} className="mt-8 space-y-3 border-t pt-5"><input type="hidden" name="id" value={paper.id} /><Textarea name="rejectionReason" placeholder="เหตุผลที่ปฏิเสธ" required /><Button type="submit" variant="destructive">ปฏิเสธพร้อมเหตุผล</Button></form><form action={approveSubmission.bind(null, paper.id)} className="mt-3"><Button type="submit">อนุมัติ</Button></form></section><form action={approveSubmissionWithEdits} className="space-y-4 rounded-lg border bg-card p-5"><h2 className="text-xl font-semibold">แก้ไขและอนุมัติ</h2><input type="hidden" name="id" value={paper.id} /><Input name="titleTh" defaultValue={paper.titleTh} placeholder="ชื่อเรื่องภาษาไทย" required /><Input name="titleEn" defaultValue={paper.titleEn ?? ""} placeholder="ชื่อเรื่องภาษาอังกฤษ" /><Textarea name="abstractTh" defaultValue={paper.abstractTh} rows={7} required /><Textarea name="abstractEn" defaultValue={paper.abstractEn ?? ""} rows={4} /><div className="grid gap-3 sm:grid-cols-2"><Input name="academicYear" type="number" defaultValue={paper.academicYear} /><Input name="semester" type="number" defaultValue={paper.semester ?? ""} /></div><Input name="researchAreaId" defaultValue={paper.researchArea.id} placeholder="Research area ID" required /><Input name="authorIds" defaultValue={ids("authors")} placeholder="Author IDs" /><Input name="advisorIds" defaultValue={ids("advisors")} placeholder="Advisor IDs" /><Input name="keywordIds" defaultValue={ids("keywords")} placeholder="Keyword IDs" /><Input name="technologyIds" defaultValue={ids("technologies")} placeholder="Technology IDs" /><select name="accessLevel" defaultValue={paper.accessLevel} className="h-9 w-full rounded-md border bg-background px-3"><option value="PUBLIC">สาธารณะ</option><option value="AUTHENTICATED">ต้องเข้าสู่ระบบ</option><option value="DEPT_ONLY">เฉพาะภาควิชา</option></select><Button type="submit">อนุมัติพร้อมแก้ไข</Button></form></div></main>;
}
