"use client";

import { useTransition } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { saveSubmission, submitSubmission } from "./actions";
import { Field } from "@/app/admin/papers/paper-form";

type Option = { id: string; name: string };
type Paper = { id: string; titleTh: string; titleEn: string | null; abstractTh: string; abstractEn: string | null; academicYear: number; semester: number | null; accessLevel: "PUBLIC" | "AUTHENTICATED" | "DEPT_ONLY"; researchAreaId: string; authors: { authorId: string }[]; advisors: { advisorId: string }[]; keywords: { keywordId: string }[]; technologies: { technologyId: string }[] };
type Props = { paper?: Paper | null; options: { areas: Option[]; authors: Option[]; advisors: Option[]; keywords: Option[]; technologies: Option[] } };

export function SubmissionForm({ options, paper }: Props) {
  const [pending, startTransition] = useTransition();
  const submit = (handler: (data: FormData) => Promise<{ ok: boolean; id: string }>) => (data: FormData) => startTransition(async () => { try { await handler(data); toast.success(handler === submitSubmission ? "ส่งให้เจ้าหน้าที่ตรวจสอบแล้ว" : "บันทึกฉบับร่างแล้ว"); } catch (error) { toast.error(error instanceof Error ? error.message : "ไม่สามารถบันทึกได้"); } });
  const select = (name: string, items: Option[], defaultValue = "") => <select name={name} defaultValue={defaultValue} className="h-9 w-full rounded-md border bg-background px-3" required={name === "researchAreaId"}><option value="">เลือก</option>{items.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select>;
  const ids = (key: "authors" | "advisors" | "keywords" | "technologies") => paper?.[key].map((item) => "authorId" in item ? item.authorId : "advisorId" in item ? item.advisorId : "keywordId" in item ? item.keywordId : item.technologyId).join(",") ?? "";
  return <form className="mt-8 space-y-6" encType="multipart/form-data"><input type="hidden" name="id" value={paper?.id ?? ""} /><section className="space-y-4 rounded-lg border bg-card p-5"><h2 className="text-xl font-semibold">ขั้นที่ 1: ข้อมูลหลัก</h2><Field label="ชื่อเรื่องภาษาไทย" name="titleTh" placeholder="ชื่อเรื่องภาษาไทย" defaultValue={paper?.titleTh} required /><Field label="ชื่อเรื่องภาษาอังกฤษ" name="titleEn" placeholder="ชื่อเรื่องภาษาอังกฤษ" defaultValue={paper?.titleEn ?? ""} /><label className="block space-y-1 text-sm"><span>บทคัดย่อภาษาไทย</span><Textarea name="abstractTh" placeholder="บทคัดย่อภาษาไทย" defaultValue={paper?.abstractTh} rows={7} required /></label><label className="block space-y-1 text-sm"><span>บทคัดย่อภาษาอังกฤษ</span><Textarea name="abstractEn" placeholder="บทคัดย่อภาษาอังกฤษ" defaultValue={paper?.abstractEn ?? ""} rows={5} /></label><div className="grid gap-4 sm:grid-cols-3"><Field label="ปีการศึกษา พ.ศ." name="academicYear" type="number" placeholder="ปีการศึกษา พ.ศ." defaultValue={paper?.academicYear} required /><Field label="ภาคเรียน" name="semester" type="number" placeholder="ภาคเรียน" defaultValue={paper?.semester ?? ""} /><label className="space-y-1 text-sm"><span>หมวดงานวิจัย</span>{select("researchAreaId", options.areas, paper?.researchAreaId)}</label></div></section><section className="space-y-4 rounded-lg border bg-card p-5"><h2 className="text-xl font-semibold">ขั้นที่ 2: ผู้จัดทำและที่ปรึกษา</h2><Field label="รหัสผู้จัดทำ" name="authorIds" defaultValue={ids("authors")} placeholder="รหัสผู้จัดทำคั่นด้วยจุลภาค" /><Field label="รหัสอาจารย์ที่ปรึกษา" name="advisorIds" defaultValue={ids("advisors")} placeholder="รหัสอาจารย์คั่นด้วยจุลภาค" /><Field label="รหัสคำสำคัญ" name="keywordIds" defaultValue={ids("keywords")} placeholder="รหัสคำสำคัญคั่นด้วยจุลภาค" /><Field label="รหัสเทคโนโลยี" name="technologyIds" defaultValue={ids("technologies")} placeholder="รหัสเทคโนโลยีคั่นด้วยจุลภาค" /></section><section className="space-y-4 rounded-lg border bg-card p-5"><h2 className="text-xl font-semibold">ขั้นที่ 3: สิทธิ์การเผยแพร่</h2><select name="accessLevel" className="h-9 w-full rounded-md border bg-background px-3" defaultValue={paper?.accessLevel ?? "AUTHENTICATED"}><option value="PUBLIC">สาธารณะ</option><option value="AUTHENTICATED">ต้องเข้าสู่ระบบ</option><option value="DEPT_ONLY">เฉพาะภาควิชา</option></select><label className="flex items-start gap-2 text-sm"><input name="consent" type="checkbox" className="mt-1" /><span>ข้าพเจ้ายินยอมให้ภาควิชาวิทยาการคอมพิวเตอร์ มหาวิทยาลัยพะเยา จัดเก็บ ตรวจสอบ และเผยแพร่ภาคนิพนธ์ตามระดับการเข้าถึงที่เลือก</span></label></section><div className="flex flex-wrap gap-3"><Button type="submit" formAction={submit(saveSubmission)} disabled={pending} variant="outline">บันทึกฉบับร่าง</Button><Button type="submit" formAction={submit(submitSubmission)} disabled={pending}>ส่งตรวจสอบ</Button></div></form>;
}
