import Link from "next/link";
import { archivePaper } from "../actions";
import { ArchiveButton } from "../admin-action";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { getAdminPapers } from "@/server/admin";

type Props = { searchParams: Promise<Record<string, string | undefined>> };
export default async function AdminPapers({ searchParams }: Props) {
  const p = await searchParams;
  const page = Number(p.page ?? 1);
  const data = await getAdminPapers({ q: p.q, status: p.status as "DRAFT" | "PUBLISHED" | "ARCHIVED" | undefined, year: p.year ? Number(p.year) : undefined, accessLevel: p.accessLevel as "PUBLIC" | "AUTHENTICATED" | "DEPT_ONLY" | undefined, sort: p.sort as "newest" | "downloads" | undefined, page });
  return <div className="space-y-6"><div className="flex items-center justify-between"><div><h1 className="text-3xl font-bold">จัดการภาคนิพนธ์</h1><p className="mt-1 text-muted-foreground">ทั้งหมด {data.total} รายการ</p></div><Button render={<Link href="/admin/papers/new" />}>เพิ่มภาคนิพนธ์</Button></div><form className="grid gap-3 rounded-lg border bg-card p-4 sm:grid-cols-5"><Input name="q" defaultValue={p.q} placeholder="ค้นหา..." /><Input name="year" defaultValue={p.year} placeholder="ปีการศึกษา" /><select name="status" defaultValue={p.status ?? ""} className="rounded-md border bg-background px-3 text-sm"><option value="">ทุกสถานะ</option><option value="PUBLISHED">เผยแพร่แล้ว</option><option value="DRAFT">ฉบับร่าง</option><option value="ARCHIVED">เก็บถาวร</option></select><select name="accessLevel" defaultValue={p.accessLevel ?? ""} className="rounded-md border bg-background px-3 text-sm"><option value="">ทุกระดับการเข้าถึง</option><option value="PUBLIC">สาธารณะ</option><option value="AUTHENTICATED">ต้องเข้าสู่ระบบ</option><option value="DEPT_ONLY">เฉพาะภาควิชา</option></select><Button type="submit">กรอง</Button></form><div className="overflow-x-auto rounded-lg border bg-card"><table className="w-full text-sm"><thead className="border-b bg-muted/50"><tr><th className="p-3 text-left">ชื่อเรื่อง</th><th className="p-3 text-left">ปี</th><th className="p-3 text-left">สถานะ</th><th className="p-3 text-left">การเข้าถึง</th><th className="p-3 text-right">จัดการ</th></tr></thead>  <tbody>{data.items.length === 0 ? <tr><td colSpan={5} className="p-8 text-center text-muted-foreground">ไม่พบภาคนิพนธ์ตามตัวกรอง</td></tr> : data.items.map((item) => <tr key={item.id} className="border-b last:border-0"><td className="max-w-sm p-3 font-medium">{item.titleTh}</td><td className="p-3">{item.academicYear}</td><td className="p-3">{item.status}</td><td className="p-3">{item.accessLevel}</td><td className="flex justify-end gap-2 p-3"><Button size="sm" variant="outline" render={<Link href={`/admin/papers/${item.id}/edit`} />}>แก้ไข</Button><ArchiveButton action={archivePaper} id={item.id} /><Button size="sm" variant="ghost" render={<Link href={`/papers/${item.slug}`} target="_blank" />}>ดูหน้าเว็บ</Button></td></tr>)}</tbody></table></div><div className="flex justify-center gap-3">{page > 1 && <Button variant="outline" render={<Link href={`/admin/papers?page=${page - 1}`} />}>ก่อนหน้า</Button>}<span className="py-2 text-sm">หน้า {page} / {Math.max(data.totalPages, 1)}</span>{page < data.totalPages && <Button variant="outline" render={<Link href={`/admin/papers?page=${page + 1}`} />}>ถัดไป</Button>}</div></div>;
}
